# Generated by Django 5.0.1 on 2024-01-28 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('ClinicId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=255)),
                ('Contact', models.CharField(max_length=50)),
                ('Availability', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('EMail', models.EmailField(max_length=255)),
                ('Password', models.CharField(max_length=50)),
                ('UserType', models.CharField(choices=[('Patient', 'Patient'), ('Staff', 'Staff')], default='Patient', max_length=10)),
                ('IsLogin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now=True)),
                ('Time', models.CharField(choices=[('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00')], default='16:00', max_length=10)),
                ('Status', models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled'), ('Paid', 'Paid')], default='Booked', max_length=10)),
                ('ClinicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicsystem.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentId', models.AutoField(primary_key=True, serialize=False)),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('Amount', models.PositiveIntegerField(default=0)),
                ('AppointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicsystem.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ServiceId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.PositiveIntegerField(default=0)),
                ('ClinicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicsystem.clinic')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='Serviceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicsystem.service'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('NotificationId', models.AutoField(primary_key=True, serialize=False)),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('Message', models.TextField()),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicsystem.user')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='UserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicsystem.user'),
        ),
    ]
