# Generated by Django 5.0.1 on 2024-01-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='DateTime',
            field=models.DateTimeField(),
        ),
    ]
