# Generated by Django 5.0 on 2024-01-29 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicsystem', '0002_alter_appointment_date_alter_notification_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Serviceid',
            new_name='ServiceId',
        ),
    ]
